spring:
  profiles:
    active: prod

---
# Configuração para DESENVOLVIMENTO (Perfil: dev)
# Usa um banco de dados H2 em memória para testes locais.
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:celldb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
# Configuração para PRODUÇÃO (Perfil: prod)
# Conecta ao seu banco de dados real no Supabase.
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

---
# Configuração para TESTES (Perfil: test)
# Usa um banco de dados H2 em memória separado para isolar os testes..
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true